[phases.setup]
nixPkgs = ["ffmpeg", "portaudio", "python312", "git"]

[phases.build]
cmds = [
  "pip install --upgrade pip",
  "pip install --no-cache-dir python-dotenv",
  "pip install --no-cache-dir -r requirements.txt"
]

[phases.start]
cmds = ["python app.py"]
